### ISSUE TITLE
按照例子根本跑不通

### ISSUE THREAD

**Issue by hh-Ink** [VinchanGit/message-notify#2]
按照例子程序无法运行
存在的问题
1. default 的配置完全不生效（包括，channel， pipeline）
2. setChannel 和 setTemplate 需要传入的是对象，例子里还是类名

我在使用时感觉
1. default 不生效，每次都要set很麻烦，因为大部分场景下只会使用一种channel
2. set 对象写起来有些繁琐

**Comment by VinchanGit** [comment]
感谢提建议，下个子版本优化一下
